"""Deterministic governed runtime surface states."""

RUNTIME_SURFACE_STATES = (
    "RUNTIME_SURFACE_CREATED",
    "RUNTIME_SURFACE_INGRESS_VALIDATED",
    "RUNTIME_SURFACE_RUNTIME_BOUND",
    "RUNTIME_SURFACE_EXECUTION_LINKED",
    "RUNTIME_SURFACE_RESPONSE_BOUND",
    "RUNTIME_SURFACE_EGRESS_VALIDATED",
    "RUNTIME_SURFACE_COMPLETED",
    "BLOCKED",
    "FAILED",
)
SUCCESS_PATH = RUNTIME_SURFACE_STATES[:7]
