"""Deterministic governed runtime delivery finalization states."""

RUNTIME_DELIVERY_FINALIZATION_STATES = (
    "RUNTIME_DELIVERY_FINALIZATION_CREATED",
    "RUNTIME_DELIVERY_FINALIZATION_EXECUTION_VALIDATED",
    "RUNTIME_DELIVERY_FINALIZATION_DELIVERY_VALIDATED",
    "RUNTIME_DELIVERY_FINALIZATION_BOUND",
    "RUNTIME_DELIVERY_FINALIZATION_FINALIZED",
    "RUNTIME_DELIVERY_FINALIZATION_CLOSED",
    "RUNTIME_DELIVERY_FINALIZATION_BLOCKED",
    "RUNTIME_DELIVERY_FINALIZATION_REJECTED",
    "FAILED",
)

SUCCESS_PATH = RUNTIME_DELIVERY_FINALIZATION_STATES[:6]
