"""Deterministic serving gateway states."""

SERVING_GATEWAY_STATES = (
    "SERVING_GATEWAY_CREATED",
    "SERVING_INGRESS_ACCEPTED",
    "SERVING_CONTINUITY_VALIDATED",
    "SERVING_RUNTIME_LINKED",
    "SERVING_TERMINAL_LINKED",
    "SERVING_RESPONSE_READY",
    "SERVING_RESPONSE_EMITTED",
    "BLOCKED",
    "FAILED",
)

SUCCESS_PATH = SERVING_GATEWAY_STATES[:7]
