[pytest]
testpaths =
    tests
    sapianta-domain-credit/tests
    sapianta-domain-trading/tests
pythonpath =
    .
    sapianta_system
    sapianta-domain-credit
    sapianta-domain-trading/src
norecursedirs =
    .git
    .mypy_cache
    .pytest_cache
    .tox
    .venv
    venv
    sapianta_system/venv
