"""Deterministic governed execution relay states."""

EXECUTION_RELAY_STATES = (
    "EXECUTION_RELAY_CREATED",
    "EXECUTION_RELAY_EXCHANGE_BOUND",
    "EXECUTION_RELAY_STDIN_LINKED",
    "EXECUTION_RELAY_STDOUT_LINKED",
    "EXECUTION_RELAY_RESULT_CAPTURED",
    "EXECUTION_RELAY_RESPONSE_EMITTED",
    "BLOCKED",
    "FAILED",
)

SUCCESS_PATH = EXECUTION_RELAY_STATES[:6]
