"""Runtime attachment states."""

ATTACHMENT_STATES = (
    "ATTACHMENT_REQUEST_RECEIVED","ATTACHMENT_RUNTIME_BOUND","ATTACHMENT_CONTINUITY_VALIDATED",
    "ATTACHMENT_INTERACTION_LINKED","ATTACHMENT_PROVIDER_LINKED","ATTACHMENT_RESPONSE_BOUND",
    "ATTACHMENT_RUNTIME_EMITTED","BLOCKED","FAILED",
)
SUCCESS_PATH = ATTACHMENT_STATES[:7]
