"""Deterministic governed runtime operational entrypoint states."""

RUNTIME_OPERATIONAL_ENTRYPOINT_STATES = (
    "RUNTIME_OPERATIONAL_ENTRY_CREATED",
    "RUNTIME_OPERATIONAL_ENTRY_VALIDATED",
    "RUNTIME_OPERATIONAL_ENTRY_BOUND",
    "RUNTIME_OPERATIONAL_ENTRY_ACTIVATED",
    "RUNTIME_OPERATIONAL_ENTRY_REALIZED",
    "RUNTIME_OPERATIONAL_ENTRY_RESPONSE_BOUND",
    "RUNTIME_OPERATIONAL_ENTRY_FINALIZED",
    "BLOCKED",
    "FAILED",
)
FINALIZED_PATH = RUNTIME_OPERATIONAL_ENTRYPOINT_STATES[:7]
