"""Deterministic governed runtime activation gate states."""

RUNTIME_ACTIVATION_GATE_STATES = (
    "RUNTIME_ACTIVATION_PENDING",
    "RUNTIME_ACTIVATION_BOUNDARY_VALIDATED",
    "RUNTIME_ACTIVATION_CONTRACT_VALIDATED",
    "RUNTIME_ACTIVATION_ADMISSION_VALIDATED",
    "RUNTIME_ACTIVATION_CONTINUITY_VALIDATED",
    "RUNTIME_ACTIVATION_APPROVED",
    "BLOCKED",
    "FAILED",
)

SUCCESS_PATH = RUNTIME_ACTIVATION_GATE_STATES[:6]
