from pathlib import Path

FIXTURE_CLASSIFICATION = "TEST_ONLY__NON_AUTHORITY__NON_OPERATIONAL__NON_EXECUTABLE"
RAW_ROOT = Path("/mnt/g77-evidence")
CONTINUATION_MANIFEST_PATH = RAW_ROOT / "G77_256IH_FUTURE_IF_BOUND_CURRENT_CANDIDATE_V1.json"
