"""Deterministic live request ingestion states."""

LIVE_REQUEST_INGESTION_STATES = (
    "LIVE_REQUEST_INGESTION_CREATED",
    "LIVE_REQUEST_ACTIVATED",
    "LIVE_REQUEST_ADMITTED",
    "LIVE_GATEWAY_CONTINUITY_VALIDATED",
    "LIVE_RUNTIME_LINKED",
    "LIVE_TERMINAL_LINKED",
    "LIVE_RESPONSE_CONTINUITY_READY",
    "BLOCKED",
    "FAILED",
)

SUCCESS_PATH = LIVE_REQUEST_INGESTION_STATES[:7]
