"""Deterministic governed terminal attachment states."""

TERMINAL_ATTACHMENT_STATES = (
    "TERMINAL_ATTACHMENT_CREATED",
    "TERMINAL_ATTACHMENT_ACTIVE",
    "TERMINAL_CONTINUITY_VALIDATED",
    "TERMINAL_STDIN_BOUND",
    "TERMINAL_STDOUT_BOUND",
    "TERMINAL_RUNTIME_LINKED",
    "TERMINAL_RESPONSE_EMITTED",
    "BLOCKED",
    "FAILED",
)

SUCCESS_PATH = TERMINAL_ATTACHMENT_STATES[:7]
