"""Persistent governed session runtime states."""

SESSION_RUNTIME_STATES = (
    "SESSION_RUNTIME_CREATED","SESSION_RUNTIME_ATTACHED","SESSION_RUNTIME_CONTINUITY_VALIDATED",
    "SESSION_RUNTIME_ACTIVE","SESSION_RUNTIME_TURN_BOUND","SESSION_RUNTIME_RESPONSE_EMITTED","BLOCKED","FAILED",
)
SUCCESS_PATH = SESSION_RUNTIME_STATES[:6]
