"""Deterministic governed execution exchange states."""

EXECUTION_EXCHANGE_STATES = (
    "EXECUTION_EXCHANGE_CREATED",
    "EXECUTION_EXCHANGE_REQUEST_BOUND",
    "EXECUTION_EXCHANGE_RUNTIME_VALIDATED",
    "EXECUTION_EXCHANGE_TERMINAL_LINKED",
    "EXECUTION_EXCHANGE_RESULT_CAPTURED",
    "EXECUTION_EXCHANGE_RESPONSE_EMITTED",
    "BLOCKED",
    "FAILED",
)

SUCCESS_PATH = EXECUTION_EXCHANGE_STATES[:6]
