"""Live governed interaction runtime states."""

RUNTIME_STATES = (
    "LIVE_REQUEST_RECEIVED","LIVE_SESSION_BOUND","LIVE_CONTINUITY_VALIDATED","LIVE_EXECUTION_LINKED",
    "LIVE_PROVIDER_ACTIVE","LIVE_RESULT_CAPTURED","LIVE_RESPONSE_EMITTED","BLOCKED","FAILED",
)
SUCCESS_PATH = RUNTIME_STATES[:7]
