"""Deterministic local runtime bridge states."""

LOCAL_RUNTIME_BRIDGE_STATES = (
    "LOCAL_RUNTIME_BRIDGE_CREATED",
    "LOCAL_RUNTIME_BRIDGE_RELAY_BOUND",
    "LOCAL_RUNTIME_BRIDGE_TRANSPORT_LINKED",
    "LOCAL_RUNTIME_BRIDGE_RUNTIME_ATTACHED",
    "LOCAL_RUNTIME_BRIDGE_RESULT_CAPTURED",
    "LOCAL_RUNTIME_BRIDGE_RESPONSE_EMITTED",
    "BLOCKED",
    "FAILED",
)

SUCCESS_PATH = LOCAL_RUNTIME_BRIDGE_STATES[:6]
