"""Governed interaction loop states."""

LOOP_STATES = (
    "SESSION_INITIALIZED", "TURN_RECEIVED", "TURN_VALIDATED", "CONTINUITY_BOUND",
    "EXECUTION_LINKED", "RESULT_CAPTURED", "RESPONSE_EXPORTED", "TURN_COMPLETED", "BLOCKED", "FAILED",
)

SUCCESS_PATH = LOOP_STATES[:8]
