"""Deterministic direct runtime interaction states."""
DIRECT_RUNTIME_INTERACTION_STATES=("DIRECT_RUNTIME_INTERACTION_CREATED","DIRECT_RUNTIME_INTERACTION_ADMITTED","DIRECT_RUNTIME_INTERACTION_RUNTIME_BOUND","DIRECT_RUNTIME_INTERACTION_EXECUTION_LINKED","DIRECT_RUNTIME_INTERACTION_RESPONSE_BOUND","DIRECT_RUNTIME_INTERACTION_RETURNED","BLOCKED","FAILED")
SUCCESS_PATH=DIRECT_RUNTIME_INTERACTION_STATES[:6]
